site_name: Beyah Solutions
docs_dir: src
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'indigo'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/beyahsolutions'
google_analytics:
  - 'UA-69987010-1'
  - auto
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
nav:
  - About: index.md
